title: Î±breacher
description: S.T.A.R Laboratories
show_downloads: false
google_analytics: G-LJFC189LR6
remote_theme: jekyll-theme-minimalist
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
  last-modified-at:
    date-format: '%Y:%B:%A:%d:%S:%R%'
