title: srt_erm
description: S.T.A.R Laboratories
show_downloads: false
google_analytics: UA-108144808-1
remote_theme: jekyll-theme-minimalist
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
